// styles.js
export const styles = {
  swiperContainer: {
    width: "189vh",
    height: "100vh",
    position: "relative",
    overflow: "hidden",
  },
  slideContent: (bgColor) => ({
    width: "100%",
    height: "100vh",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
    color: "white",
    textAlign: "center",
    backgroundColor: bgColor,
    overflow: "hidden",
  }),
  centerContent: {
    zIndex: 3,
    position: "relative",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
  },
  productContainer: {
    cursor: "pointer",
    transition: "transform 0.5s ease",
  },
  productImg: {
    width: 250,
    transition: "all 0.5s ease",
  },
  slideTitle: {
    fontSize: "2.5rem",
    fontWeight: "bold",
    marginTop: "1rem",
    transition: "opacity 0.3s ease",
  },
  viewBtn: {
    marginTop: "1rem",
    padding: "10px 24px",
    border: "1px solid white",
    background: "transparent",
    color: "white",
    borderRadius: 50,
    transition: "all 0.3s ease",
    cursor: "pointer",
  },
  floatingExtra: {
    position: "absolute",
    width: 80,
    opacity: 0.8,
    zIndex: 2,
    cursor: "pointer",
    transition: "all 0.5s ease",
  },
  detailButtonContainer: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    zIndex: 10,
  },
  detailButton: {
    padding: "15px 30px",
    border: "2px solid white",
    background: "transparent",
    color: "white",
    borderRadius: 50,
    fontSize: "1.1rem",
    fontWeight: "bold",
    cursor: "pointer",
    transition: "all 0.3s ease",
  },
};

