// styles.js
export const styles = {
  swiperContainer: {
    width: "100%",
    height: "100vh",
    position: "relative",
    overflow: "hidden",
  },
  slideContent: (bgColor) => ({
    width: "100%",
    height: "100vh",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
    color: "white",
    textAlign: "center",
    backgroundColor: bgColor,
    overflow: "hidden",
  }),
  centerContent: {
    zIndex: 3,
    position: "relative",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
  },
  productContainer: {
    cursor: "pointer",
  },
  productImg: {
    width: 250,
  },
  slideTitle: {
    fontSize: "2.5rem",
    fontWeight: "bold",
    marginTop: "1rem",
    transition: "opacity 0.3s ease",
  },
  viewBtn: {
    marginTop: "1rem",
    padding: "10px 24px",
    border: "1px solid white",
    background: "transparent",
    color: "white",
    borderRadius: 50,
    transition: "all 0.3s ease",
    cursor: "pointer",
  },
  floatingExtra: {
    position: "absolute",
    width: 80,
    opacity: 0.8,
    zIndex: 2,
    cursor: "pointer",
    transition: "all 0.5s ease",
  },

  detailButtonContainer: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    zIndex: 10,
  },
  detailButton: {
    padding: "15px 30px",
    border: "2px solid white",
    background: "transparent",
    color: "white",
    borderRadius: 50,
    fontSize: "1.1rem",
    fontWeight: "bold",
    cursor: "pointer",
    transition: "all 0.3s ease",
  },

  glowLayer: {
    position: "absolute",
    top: "50%",
    left: "50%",
    width: "600px",
    height: "600px",
    background:
      "radial-gradient(circle, rgba(255,255,255,0.25) 0%, transparent 100%)",
    transform: "translate(-50%, -50%)",
    borderRadius: "50%",
    filter: "blur(90px)",
    zIndex: 1,
    pointerEvents: "none",
  },
  vignetteLayer: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    background:
      "radial-gradient(circle at center, transparent 50%, rgba(0, 0, 0, 0.27) 110%)",
    zIndex: 0,
    pointerEvents: "none",
  },

  /* Header Styles */
  headerContainer: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    height: "70px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "0 24px",
    zIndex: 1000,
    color: "white",
    fontFamily: "'Poppins', sans-serif",
    fontWeight: 300,
    fontSize: "14px",
  },

  logo: {
    textAlign: "center",
    fontSize: "20px",
    fontWeight: 500,
    letterSpacing: "1px",
    position: "absolute",
    left: "50%",
    transform: "translateX(-50%)",
    zIndex: 1100,
  },

  logoText: {
    color: "white",
    fontSize: "18px",
    fontWeight: 600,
  },

  iconBar: {
    display: "flex",
    alignItems: "center",
    gap: "20px",
  },

  iconButton: {
    background: "transparent",
    border: "none",
    color: "white",
    fontSize: "16px",
    cursor: "pointer",
    transition: "opacity 0.3s ease",
  },
  burgerButton: {
    background: "transparent",
    border: "none",
    color: "white",
    fontSize: "18px",
    cursor: "pointer",
    padding: "8px",
  },
  mobileMenu: {
    display: "none",
    position: "absolute",
    top: "70px",
    right: "16px",
    background: "rgba(0,0,0,0.6)",
    backdropFilter: "blur(6px)",
    borderRadius: "10px",
    padding: "8px",
    zIndex: 1200,
    minWidth: "160px",
  },
  mobileMenuItem: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    width: "100%",
    padding: "10px",
    background: "transparent",
    color: "white",
    border: "none",
    textAlign: "left",
    cursor: "pointer",
  },
};
